name: Docker Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # <--- This targets your VM runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restart Docker Containers
        run: |
          docker compose up -d --build
